### ISSUE TITLE
iOS Xcode Command Line Setup

### ISSUE THREAD

**Issue by xpnewmedia** [OneSignal/cli#44]
This library is helpful and works for the most part.
I occasionally get an error....

_Steps To Reproduce:_

- Create a New Xcode Project
- Cd to Directory in Terminal,
- Run Command
```
onesignal install-sdk --type iOS --entrypoint AppName --lang swift --appid xxxxxxxxx
```
_Error:_
```
/opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:315:in `+': no implicit conversion of nil into String (TypeError)
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:315:in `_add_capabilities_to_main_target'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:42:in `_add_sdk'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:80:in `install_onesignal!'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/oscli.rb:56:in `execute'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/bin/onesignal:4:in `<top (required)>'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/bin/onesignal:25:in `load'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/bin/onesignal:25:in `<main>'
```

What gives?
Thx

**Comment by uxshahil** [comment]
Using Mac M1 Pro 16GB Ventura 13.2.1

Steps To Reproduce:
- Locate existing Xcode project
- Cd to Directory in Terminal
- Run Command

`onesignal install-sdk --type iOS --entrypoint AppName --lang objc --appid AppId --target AppTarget`

Error: 

/opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:335:in `_add_capabilities_to_main_target': undefined method `path' for nil:NilClass (NoMethodError)

    group_relative_entitlements_path = group.path + "/" + self.target_name + ".entitlements"
                                            ^^^^^
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:42:in `_add_sdk'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/osproject_ios.rb:80:in `install_onesignal!'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/lib/oscli.rb:56:in `execute'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/gems/onesignal-cli-1.0.0/bin/onesignal:4:in `<top (required)>'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/bin/onesignal:25:in `load'
	from /opt/homebrew/Cellar/onesignal-cli/0.0.7/libexec/bin/onesignal:25:in `<main>'
